apiVersion: v1
kind: Pod
metadata:
  name: posix-mq-pod
spec:
  containers:
    - name: posix-mq-sender
      image: posix-mq-sender
      imagePullPolicy: Never
    - name: posix-mq-receiver
      image: posix-mq-receiver
      imagePullPolicy: Never
  restartPolicy: Never
